### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_all_instances'

### ISSUE THREAD

**Issue by hopewise** [joaquincasares/cassandralauncher#19]
I tried to use this image: ami-373e2b07 at us-west-2 , but I got this error:

> Traceback (most recent call last):
>   File "/usr/local/bin/cassandralauncher", line 4, in <module>
>     cassandralauncher.CassandraLauncher()
>   File "/usr/local/lib/python2.7/dist-packages/cassandralauncher/**init**.py", line 6, in **init**
>     cassandralauncher.run()
>   File "/usr/local/lib/python2.7/dist-packages/cassandralauncher/cassandralauncher.py", line 751, in run
>     main()
>   File "/usr/local/lib/python2.7/dist-packages/cassandralauncher/cassandralauncher.py", line 561, in main
>     ec2.terminate_cluster(check_cascading_options('aws_access_key_id'), check_cascading_options('aws_secret_access_key'), config.get('EC2', 'placement'), check_cascading_options('handle'), prompt_continuation=True)
>   File "/usr/local/lib/python2.7/dist-packages/cassandralauncher/ec2.py", line 248, in terminate_cluster
>     reservations = conn.get_all_instances()
> AttributeError: 'NoneType' object has no attribute 'get_all_instances'

Any idea?

**Comment by joaquincasares** [comment]
Hi @hopewise ,

The code that calls that stacktrace looks pretty simple:

https://github.com/joaquincasares/cassandralauncher/blob/master/cassandralauncher/ec2.py#L240-L248

When looking at the boto API, I found this quote here: 

> Returns:  A connection to the given region, or None if an invalid region name is given

Source: http://boto.cloudhackers.com/en/latest/ref/ec2.html#boto.ec2.connect_to_region

Could you confirm your region name is valid?

Also, I haven't worked on this project in a while and unless you create a fork and maintain a reflector, this project will stop working in December: 

https://github.com/riptano/ComboAMI

Also interesting to note, `get_all_instances()` is deprecated in favor of `get_all_reservations()`, in case you have any issues in the future:

http://boto.cloudhackers.com/en/latest/ref/ec2.html#boto.ec2.connection.EC2Connection.get_all_instances

Hope that helps!

Joaquin

**Comment by hopewise** [comment]
Thank you Joaquin

**Comment by joaquincasares** [comment]
Sure thing!
